name: flutter_application_5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  url_launcher: ^6.3.2
  http: ^1.2.0
  speech_to_text: ^7.4.0
  flutter_tts: ^4.2.5
  audioplayers: ^6.8.1
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # استدعاء كافة الصور والفيديوهات داخل مجلد photo دفعة واحدة
  assets:
    - photo/

flutter_launcher_icons:
  image_path: "photo/1.png"
  android: true
  ios: true
  adaptive_icon_background: "#ffffff" # لون خلفية الأيقونة المتكيفة (يمكنك تغييره حسب رغبتك مثل #000000)
  adaptive_icon_foreground: "photo/1.png" # نفس الصورة أو صورة مخصصة للطبقة الأمامية